export const initialBreeds = {
  adaptability: 5,
  affection_level: 5,
  alt_names: 'York',
  child_friendly: 4,
  country_code: 'US',
  country_codes: 'US',
  description:
    "York Chocolate cats are known to be true lap cats with a sweet temperament. They love to be cuddled and petted. Their curious nature makes them follow you all the time and participate in almost everything you do, even if it's related to water: unlike many other cats, York Chocolates love it.",
  dog_friendly: 5,
  energy_level: 5,
  experimental: 0,
  grooming: 3,
  hairless: 0,
  health_issues: 1,
  hypoallergenic: 0,
  id: 'ycho',
  image: {
    id: '0SxW2SQ_S',
    width: 800,
    height: 1203,
    url: 'https://cdn2.thecatapi.com/images/0SxW2SQ_S.jpg',
  },
  indoor: 0,
  intelligence: 5,
  lap: 1,
  life_span: '13 - 15',
  name: 'York Chocolate',
  natural: 0,
  origin: 'United States',
  rare: 0,
  reference_image_id: '0SxW2SQ_S',
  rex: 0,
  shedding_level: 3,
  short_legs: 0,
  social_needs: 4,
  stranger_friendly: 4,
  suppressed_tail: 0,
  temperament: 'Playful, Social, Intelligent, Curious, Friendly',
  vocalisation: 5,
  weight: { imperial: '12 - 18', metric: '5 - 8' },
  wikipedia_url: 'https://en.wikipedia.org/wiki/York_Chocolate',
};
